- name: setup hosts
  hosts: all
  connection: local
  become: true
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Install zip and unzip
      apt:
        name: [ "zip", "unzip" ]
        state: latest
        update_cache: yes
    - name: Install awscli
      apt:
        name: awscli
        state: latest
    - name: "Install python-pip and virtual envirnment"
      apt:
        name: [ "python3-pip", "python3-venv" ]
      #shell:
        #"apt install xubuntu-core^"
    - name: "Install Python dev and related utils"
      apt:
        name: [ "python3-dev", "libsasl2-dev", "gcc" ]
        state: latest
    - name: "Install the Java Development Kit"
      apt:
        name: openjdk-11-jdk
        state: latest
    - name: Detect if NPM (the Nodejs Package Manager) is installed
      shell: "which npm | wc -c"
      register: is_npm_present
    - name: Install the apt-repository for v16.x nodejs/npm, only if not already installed
      shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
      args:
        warn: false
      when: is_npm_present["stdout"] == "0"
    - name: Install nodejs and npm v16.x , only if not already installed
      apt:
        name: nodejs
        state: latest
      when: is_npm_present["stdout"] == "0"
    - name: Install the AWS CDK node.js package globally.
      community.general.npm:
        name: aws-cdk
        global: yes


